spring:
  application:
    name: team-oil-user
  profiles:
    active: dev
server:
  port: 1655
logging:
  file:
    name: logs/user_oil/user_oil.log
  level:
#    root: debug
    com.ouyu.tech.team_oil.user_oil: debug
mybatis-plus:
  type-aliases-package: com.ouyu.tech.team_oil.user_oil.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
#    禁用httpclient 启用okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
#    开启压缩可以节约网络资源，提升接口性能 使用的是Gzip
  compression:
    request:
      enabled: true
    response:
      enabled: true
#      开启hystrix熔断服务
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
unify:
  exception-handler:
    enable: true
