spring:
  application:
    name: team-oil-order
  profiles:
    active: dev
server:
  port: 1654
logging:
  file:
    name: logs/order_oil/order_oil.log
  level:
    com.ouyu.tech.team_oil.order_oil: debug
mybatis-plus:
  type-aliases-package: com.ouyu.tech.team_oil.order_oil.entity
  mapper-locations: classpath*://mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true